name: NLP2024
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jupyter_client=8.6.1
  - jupyter_core=5.5.0
  - libcxx=16.0.6
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.2.1
  - packaging=24.0
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.10.13
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.14.2
  - typing_extensions=4.10.0
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==0.28.0
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - datasets==2.18.0
      - dill==0.3.8
      - evaluate==0.4.1
      - filelock==3.13.1
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - huggingface-hub==0.21.4
      - idna==3.6
      - jinja2==3.1.3
      - joblib==1.3.2
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.2.1
      - nltk==3.8.1
      - numpy==1.26.4
      - pandas==2.2.1
      - psutil==5.9.8
      - pyarrow==15.0.2
      - pyarrow-hotfix==0.6
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests==2.31.0
      - responses==0.18.0
      - rouge-score==0.1.2
      - safetensors==0.4.2
      - sentencepiece==0.2.0
      - sympy==1.12
      - tokenizers==0.15.2
      - torch==2.2.1
      - tqdm==4.66.2
      - transformers==4.39.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - xxhash==3.4.1
      - yarl==1.9.4
      - seqeval
